apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  namespace: {{ .Values.namespace }}
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - name: {{ .Values.mysql }}
        image: {{ .Values.mysql.deployment.image }}
        ports:
        - name: mysql
          containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mysql.secret.name }}
              key: {{ .Values.mysql.data.password }} 
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/mysql
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: {{ .Values.mysql.pvc.name}}
