apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.wordpress }}
  namespace: {{ .Values.namespace }}
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - name: wordpress
        image: {{ .Values.wordpress.deployment.image }}
        ports:
          - name: http
            containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mysql.secrets.name }}
              key: {{ .Values.mysql.data.password }}
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: {{ template "wppvc" . }}
