apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  namespace: {{ .Values.namespace }}
  labels:
    app: wordpress
spec:
  accessModes:
    - {{ .Values.mysql.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.mysql.pvc.storage }}
